.Dd October 29, 2024
.Dt HCP 1
.Os
.Sh NAME
.Nm hcp
.Nd Copy files using Hercules
.Sh SYNOPSIS
.Nm hcp
.Bk -words
.Op OPTIONS
.Ar SOURCE-API
.Ar SOURCE-PATH
.Ar DEST-ADDR
.Ar DEST-PATH
.Ek
.Sh DESCRIPTION
.Nm
is an easy-to-use tool to copy files using the Hercules file transfer system.
It interacts with the Hercules server's API on behalf of the user.
It instructs the source Hercules server, whose API is exposed on
.Ar SOURCE-API
to transfer the file (or directory)
.Ar SOURCE-PATH
to the destination Hercules server whose SCION/UDP address is
.Ar DEST-ADDR
and store it under
.Ar DEST-PATH .
Once a transfer is submitted,
.Nm
will periodically poll the Hercules server for information about the transfer's
progress and show this information to the user.
.Pp
Note that the paths must be supplied from the point of view of the source and
destination Hercules servers, respectively.
If
.Nm
is run from a different machine than the source Hercules server, the source file
must first be made available to the Hercules server.
Doing so is outside the scope of this tool,
but this may be achieved by means of a network mount, or by attaching storage
media containing the file to the machine running the Hercules server.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl i Ar poll_freq
How frequently to poll the server for transfer status updates.
The argument is a go duration string.
The default polling frequency is
.Ar 1s ,
that is, poll every second.
.It Fl n
Do not ask the server for the file's total size before submitting the transfer.
With this option set, the progress bar and time estimates are not shown.
.It Fl version
Print version information and exit.
.El
.\" .Sh EXIT STATUS
.Sh EXAMPLES
If you are running this tool on the same machine as the source
Hercules server and want to transfer the file
.Pa /tmp/hercules.in
to
.Pa /tmp/hercules.out ,
with the destination Hercules server listening on
.Ar 64-2:0:9,192.168.4.2:10000 ,
run the following command:
.Pp
.Dl $ hcp localhost:8000 /tmp/hercules.in 64-2:0:9,192.168.4.2:10000 \
/tmp/hercules.out
.Pp
If your are running the Hercules server on a dedicated machine, with its API
accessible on
.Ar 10.0.0.1:8000 ,
you have copied the file you want to transfer,
.Pa hercules.in ,
to a network share mounted at
.Pa /mnt/data
on the Hercules server, and want to submit run hcp from a different host:
.Pp
.Dl $ hcp 10.0.0.1:8000 /mnt/data/hercules.in 64-2:0:9,192.168.4.2:10000 \
/tmp/hercules.out
.\" .Sh DIAGNOSTICS
.Sh SEE ALSO
.Xr hercules-monitor 1 ,
.Xr hercules-server 1 ,
.Xr hercules.conf 5 ,
.Xr hercules 7
.Pp
Further information about Hercules is available on
.Lk https://github.com/netsec-ethz/hercules .
For more information about SCION, please see
.Lk https://scion-architecture.net .
.\" .Sh CAVEATS
.Sh AUTHORS
.An Network Security Group, ETH Zürich
