# Sample config for Hercules monitor

# By default, up to `DefaultNumPaths` paths will be used.
DefaultNumPaths = 1

# Path to the monitor's unix socket
MonitorSocket = "var/run/herculesmon.sock"
#
# Path to the server's unix socket
ServerSocket = "var/run/hercules.sock"

# SCION address the Hercules server should listen on
ListenAddress = "17-ffaa:1:fe2,192.168.10.141:8000"

# Network interfaces to use for Hercules
Interfaces = [
"eth0",
]

# If the NIC/drivers support XDP in zerocopy mode, enabling it
# will improve performance.
XDPZeroCopy = true

# Specify the NIC RX queue on which to receive packets
Queue = 0

# For Hercules to receive traffic, packets must be redirected to the queue
# specified above. Hercules will try to configure this automatically, but this
# behaviour can be overridden, e.g. if you wish to set custom rules or automatic
# configuration fails. If you set this to false, you must manually ensure
# packets end up in the right queue.
ConfigureQueues = false

# Disabling congestion control is possible, but probably a bad idea
EnablePCC = false

# This sets a sending rate limit (in pps)
# that applies to all transfers individually
RateLimit = 100000

# The number of RX/TX worker threads to use
NumThreads = 2

# The number and choice of paths can be overridden on a destination-host
# or destination-AS basis. In case both an AS and Host rule match, the Host
# rule takes precedence.

# This Host rule specifies that, for the host 17-ffaa:1:fe2,1.1.1.1,
# - Transfers may use up to 42 paths
# - The paths must contain either the AS-interface sequence
#       17-f:f:f 1 > 17:f:f:a 2
#       OR 1-f:0:0 22
[[DestinationHosts]]
HostAddr = "17-ffa:1:fe2,1.1.1.1"
NumPaths = 42
PathSpec = [
["17-f:f:f 1", "17-f:f:a 2"],
["1-f:0:0 22"],
]

# In this case the number of paths is set to 2, but the exact set of paths
# is left unspecified
[[DestinationHosts]]
HostAddr = "18-a:b:c,2.2.2.2"
NumPaths = 2


# Similarly, but for an entire destination AS instead of a specific host
[[DestinationASes]]
IA = "17-a:b:c"
NumPaths = 2
